### ISSUE TITLE
[Feature] Auto-load binaries for plugins

### ISSUE THREAD

**Issue by AlexSkilled** [easyp-tech/easyp#120]
# Automatically download and install binaries for plugins

### Config
```yaml
generate:
    plugins:
        - name: grpc-gateway
          out: pkg
          install_script: go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.25.1
       
        - name: gen-ts
          out: pkg/web
          install_script: npm install -g protoc-gen-ts
```

## 2. Defining package link / source 
This way is a bit harder to implement, but I like it way much

Defining plugin's source in config
### Config
```yaml
generate:
    plugins:
        - name: grpc-gateway
          out: pkg
          plugin_src: github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.25.1
       
        - name: gen-ts
          out: pkg/web
          plugin_src: protoc-gen-ts@0.8.7
```
And resolve it as Npm Package / Golang project / etc. 
Information about plugin can be cached at "easyp.lock"  

## Also
- Include installed package to easyp.lock and use lock-file when running scripts
- Define "well-known" plugin sources (google.golang.org/protobuf/cmd/protoc-gen-go for golang and etc)
- For second option maybe it is better to install binaries into EASYPPATH (npm-like way. 
In my projects I prefer to hold downloaded dependencies in the repo like node_modules)   

Can implement it myself.
