### ISSUE TITLE
[BUG] ENUM_VALUE_UPPER_SNAKE_CASE doesn't allow numbers in name prefix.

### ISSUE THREAD

**Issue by amanize** [easyp-tech/easyp#130]
Describe the bug
Rule `ENUM_VALUE_UPPER_SNAKE_CASE` doesn't allow using number in enum values naming.

Rule regexp doesn't contains number:

```go
upperSnakeCase := regexp.MustCompile("^[A-Z]+(_[A-Z]+)*$")
```

[Link to code](https://github.com/easyp-tech/easyp/blob/main/internal/rules/enum_value_upper_snake_case.go#L22C2-L22C60).

To Reproduce
1. Execute command 'easyp --cfg easyp.yaml lint'
2. Pass the argument 'easyp.yaml'
  - `easyp.yaml` source:
```yaml
version: v1
lint:  
  use:
    # minimal
    - DIRECTORY_SAME_PACKAGE
    - PACKAGE_DEFINED
    - PACKAGE_DIRECTORY_MATCH
    - PACKAGE_SAME_DIRECTORY
    # Basic
    - ENUM_FIRST_VALUE_ZERO
    - ENUM_NO_ALLOW_ALIAS
    - ENUM_PASCAL_CASE
    - ENUM_VALUE_UPPER_SNAKE_CASE
    - FIELD_LOWER_SNAKE_CASE
    - IMPORT_NO_PUBLIC
    - IMPORT_NO_WEAK
    - IMPORT_USED
    - MESSAGE_PASCAL_CASE
    - ONEOF_LOWER_SNAKE_CASE
    - PACKAGE_LOWER_SNAKE_CASE
    # Default
    - ENUM_VALUE_PREFIX
    #    - ENUM_ZERO_VALUE_SUFFIX  # not sure that it need
    - FILE_LOWER_SNAKE_CASE
    - RPC_REQUEST_RESPONSE_UNIQUE
    - RPC_REQUEST_STANDARD_NAME
    - RPC_RESPONSE_STANDARD_NAME
    - PACKAGE_VERSION_SUFFIX
    - SERVICE_SUFFIX
    # Comments
    - COMMENT_ENUM
    #    - COMMENT_ENUM_VALUE  # naughty
    #    - COMMENT_FIELD  # naughty
    - COMMENT_MESSAGE
    - COMMENT_ONEOF
    - COMMENT_RPC
    - COMMENT_SERVICE

deps:
  - github.com/googleapis/googleapis@v0.0.0-20240511133251-f7df662a24c56ecaab79cb7d808fed4d2bb4981d
  - github.com/bufbuild/protovalidate@v0.3.1

generate:
  deps:
    - lint  
  plugins:
    - name: go
      out: ./golang
      opts:
        paths: source_relative    
  ```
3. Include the proto file 'enum.proto'
  - `enum.proto` source
```proto
syntax = "proto3";

option go_package = "proto/enums";

package proto.v1; 

/* TestEnum comment. */
enum TestEnum{
    /* Unknown comment. */
    TEST_ENUM_UNKNOWN = 0;
    /* S3 comment. */
    TEST_ENUM_S3_OBJECT = 1;
    /* K8s comment. */
    TEST_ENUM_K8S_NODE = 2;
}
```
4. Observe the error
```bash
proto/v1/enum.proto:12:5:TEST_ENUM_S3_OBJECT: enum value is not upper snake case
proto/v1/enum.proto:14:5:TEST_ENUM_K8S_NODE: enum value is not upper snake case
```
Expected behavior
Rule `ENUM_VALUE_UPPER_SNAKE_CASE` allow using if numbers in enum values naming.

Log files
If applicable, add log files to help explain your problem.

Desktop (please complete the following information):
 - OS: e.g. Windows 11
   - WSL2: Ubuntu 22.04.5 LTS
 - easyp v0.7.7

Additional context
No additional context.

Attachments
Complete example, includes proto, easyp binary and easyp.yaml
[example.tar.gz](https://github.com/user-attachments/files/18376144/example.tar.gz)
