### ISSUE TITLE
[BUG] Git packages are not updated on version change

### ISSUE THREAD

**Issue by cadabrum** [easyp-tech/easyp#146]
Describe the bug
Git packages are not updated on version change.

To Reproduce:

Initial state:
```
lint:
    use:
        - DEFAULT
    enum_zero_value_suffix: _NONE
    service_suffix: API
    ignore: []
    except: []
    allow_comment_ignores: false
    ignore_only: {}
deps: []
generate:
    inputs:
    - git_repo:
        url: "my-private-repo.example/my_project/my-proto@v0.0.1"
    plugins:
    - name: python
      out: ./proto
    - name: mypy
      out: ./proto
```

easyp generate - ok
easyp mod vendor - ok

After changing the version in the config to v0.0.2:
easyp mod vendor - vendors files from v0.0.1
easyp mod update 
easyp mod dowload 
easyp mod vendor - again, vendors files from v0.0.1

easyp generate - only this step triggers the version update
easyp mod vendor - vendors files from v0.0.2

Expected behavior
The versions of the vendored packages should match the versions specified in the config.

 - CLI Tool version:  v0.7.13
